# Process pull request workflow

name: Process-Pull-Request

on: [pull_request_target]
  types: [assigned, unassigned, opened, edited, synchronize, reopened]

jobs:
  process-pull-request:
    
    runs-on: ubuntu-latest

    steps:

      - name: get-status
        shell: bash
        run: echo "target branch = $github.base_ref"
        run: echo "source branch = $github.head_ref"
        run: echo "review state = $github.event.pull_request_target.state"
        run: echo "action = $github.event.pull_request_target.action"
